apiVersion: v1
name: sagemaker-k8s-trainingjob
version: 0.1.0
description: A Helm chart for deploying the SageMaker Hyperparameter tuning job for Kubernetes.
maintainers:
  - name: Gautam Kumar
    email: gauta@amazon.com
  - name: Cade Daniel
    email: cdnamz@amazon.com
